<?
if (INCLUDED!==true) { include('index.htm'); exit; }

$MAP = Array(
0 => 'Eastern Kingdoms',
1 => 'Kalimdor',
13 => 'Testing',
25 => 'Scott Test',
30 => 'Alterac Valley',
33 => 'Shadowfang',
34 => 'Stormwind Jail',
35 => 'Stormwind Prison',
36 => 'Deadmines',
37 => 'Azshara Crater',
42 => 'Collin',
43 => 'Wailing Caverns',
44 => 'Monastery',
47 => 'Razorfen Kraul',
48 => 'Blackfathom',
70 => 'Uldaman',
90 => 'Gnomeregan',
109 => 'Sunken Temple',
129 => 'Razorfen Downs',
169 => 'Emerald Dream',
189 => 'Monastery',
209 => 'Tanaris',
229 => 'Blackrock Spire',
230 => 'Blackrock Depths',
249 => 'Onyxia\'s Lair',
269 => 'Caverns of time',
289 => 'School of Necromancy',
309 => 'Zul\'Gurub',
329 => 'Stratholme',
349 => 'Maraudon',
369 => 'Deeprun Tram',
389 => 'Ragefire Chasm',
409 => 'Molten Core',
429 => 'Dire Maul',
449 => 'Alliance PVP Barracks',
450 => 'Horde PVP Barracks',
451 => 'Development',
469 => 'Blackwing Lair',
489 => 'PVP Zone 3',
509 => 'Ahn\'Qiraj',
529 => 'PVP Zone 4',
530 => 'Outland',
531 => 'Ahn\'Qiraj Temple',
532 => 'Karazhan',
533 => 'Stratholme Raid',
534 => 'Hyjal Past',
540 => 'Hellfire: Military',
542 => 'Hellfire: Demon',
543 => 'Hellfire: Rampart',
544 => 'Hellfire Raid',
545 => 'Coilfang: Pumping',
546 => 'Coilfang: Marsh',
547 => 'Coilfang: Draenei',
548 => 'Coilfang Raid',
550 => 'Tempest Keep Raid',
552 => 'Tempest Keep: Arcane',
553 => 'Tempest Keep: Atrium',
554 => 'Tempest Keep: Factory',
555 => 'Auchindoun: Shadow',
556 => 'Auchindoun: Demon',
557 => 'Auchindoun: Ethereal',
558 => 'Auchindoun: Draenei',
559 => 'PVP Zone 5',
560 => 'Hillsbrad Past',
562 => 'Blade\'s Edge Arena',
564 => 'Black Temple',
565 => 'Gruul\'s Lair',
566 => 'NetherstormBG',
568 => 'Zul\'Aman',
571 => 'Northrend',
572 => 'PVP Lordaeron',
573 => 'Exterior',
574 => 'Valgarde 70',
575 => 'Utgarde Pinnacle',
576 => 'Nexus 70',
578 => 'Nexus 80',
580 => 'Sunwell Plateau',
582 => 'Transport: Rut\'theran to Auberdine',
584 => 'Transport: Magister\'s to Theramore',
585 => 'Sunwell 5 man',
586 => 'Transport: Exador to Auberdine',
587 => 'Transport: Feathermoon Ferry',
588 => 'Transport: Menethil to Auberdine',
589 => 'Transport: Orgrimmar to Grom\'Gol',
590 => 'Transport: Grom\'Gol to Undercity',
591 => 'Transport: Undercity to Orgrimmar',
592 => 'Transport: Borean Tundra Test',
593 => 'Transport: Booty Bay to Ratchet',
594 => 'Transport: Howling Fjord Sister Mercy (Quest)',
595 => 'Stratholme COT',
596 => 'Transport: Naglfar',
597 => 'Craig Test',
598 => 'Sunwell 5 man',
599 => 'Ulduar 70',
600 => 'Drak\'Tharon Keep',
601 => 'Azjol Upper City',
602 => 'Ulduar 80',
603 => 'Ulduar Raid',
604 => 'Gundrak',
605 => 'Development',
606 => 'QA and DVD',
607 => 'Northrend BG',
608 => 'Dalaran Prison',
609 => 'Death Knight Start',
610 => 'Transport: Tirisfal to Vengeance Landing',
612 => 'Transport: Menethil to Valgarde',
613 => 'Transport: Orgrimmar to Warsong Hold',
614 => 'Transport: Stormwind to Valiance Keep',
615 => 'Chamber of Aspect Black',
616 => 'Nexus Raid',
617 => 'Dalaran Arena',
618 => 'Orgrimmar Arena',
619 => 'Azjol Lower City',
620 => 'Transport: Moa\'ki to Unu`pe',
621 => 'Transport: Moa\'ki to Kamagua',
622 => 'Transport: Orgrim\'s Hammer',
623 => 'Transport: The Skybreaker',
624 => 'Wintergrasp Raid',
628 => 'Isle of Conquest',
631 => 'Icecrown Citadel',
632 => 'Icecrown Citadel 5 man',
641 => 'Transport: A Airship (BG)',
642 => 'Transport: H Airship (BG)',
647 => 'Transport: Orgrimmar to Thunderbluff',
649 => 'Argent Tournament Raid',
650 => 'Argent Tournament Dungeon',
658 => 'Pit Of Saron',
668 => 'Halls of Reflection',
672 => 'Transport: A Airship (ICC Raid)',
673 => 'Transport: H Airship (ICC Raid)',
712 => 'Transport: A Airship (ICC Dungeon)',
713 => 'Transport: H Airship (ICC Dungeon)',
718 => 'Transport: The Mighty Wind (ICC Raid)',
723 => 'Stormwind',
724 => 'Chamber if Asoects Red',

);

$ZONE = Array(
  0 => Array(
    Array(36,'Alterac Mountains'),
	Array(45,'Arathi Highlands'),
	Array(3,'Badlands'),
	Array(25,'Blackrock Mountain'),
	Array(4,'Blasted Lands'),
	Array(46,'Burning Steppes'),
	Array(41,'Deadwind Pass'),
	Array(2257,'Deeprun Tram'),
	Array(1,'Dun Morogh'),
	Array(10,'Duskwood'),
	Array(139,'Eastern Plaguelands'),
	Array(12,'Elwynn Forest'),
	Array(3430,'Eversong Woods'),
	Array(3433,'Ghostlands'),
	Array(267,'Hillsbrad Foothills'),
	Array(1537,'Ironforge'),
	Array(4080,'Isle of Quel\'Danas'),
	Array(38,'Loch Modan'),
	Array(4298,'Plaguelands: The Scarlet Enclave'),
	Array(44,'Redridge Mountains'),
	Array(51,'Searing Gorge'),
	Array(3487,'Silvermoon City'),
	Array(130,'Silverpine Forest'),
	Array(1519,'Sturmwind City'),
	Array(33,'Stranglethorn Vale'),
	Array(8,'Swamp of Sorrows'),
	Array(47,'The Hinterlands'),
	Array(85,'Tirisfal Glades'),
	Array(1497,'Undercity'),
	Array(28,'Western Plaguelands'),
	Array(40,'Westfall'),
	Array(11,'Wetlands'),
  ),
  
  1 => Array(
	Array(331,'Ashenvale'),
	Array(16,'Azshara'),
	Array(3524,'Azuremyst Isle'),
	Array(3525,'Bloodmyst Isle'),
	Array(148,'Darkshore'),
	Array(1657,'Darnassus'),
	Array(405,'Desolace'),
	Array(14,'Durotar'),
	Array(15,'Dustwallow Marsh'),
	Array(361,'Felwood'),
	Array(876,'GM Island'),
	Array(616,'Hyjal'),
	Array(493,'Moonglade'),
	Array(215,'Mulgore'),
	Array(1637,'Orgrimmar'),
	Array(1377,'Silithus'),
	Array(406,'Stonetalon Mountains'),
	Array(440,'Tanaris'),
	Array(141,'Teldrassil'),
	Array(17,'The Barrens'),
	Array(3557,'The Exodar'),
	Array(457,'The Veiled Sea'),
	Array(400,'Thousand Needles'),
	Array(1638,'Thunder Bluff'),
	Array(490,'Un\'Goro Crater'),
	Array(618,'Winterspring'),
  ),
  530 => Array(
	Array(3522,'Blade\'s Edge Mountains'),
	Array(3483,'Hellfire Peninsula'),
    Array(3518,'Nagrand'),
	Array(3523,'Netherstorm'),
	Array(3520,'Shadowmoon Valley'),	
	Array(3703,'Shattrath City'),
	Array(3519,'Terokkar Forest'),
	Array(3521,'Zangarmarsh'),
  ),
  571 => Array(
    Array(3537,'Borean Tundra'),
	Array(2817,'Crystalsong Forest'),
	Array(4395,'Dalaran'),
	Array(65,'Dragonblight'),
	Array(394,'Grizzly Hills'),
	Array(495,'Howling Fjord'),
	Array(4742,'Hrothgar\'s Landing'),
	Array(210,'Icecrown'),
	Array(3711,'Sholazar Basin'),
	Array(67,'The Storm Peaks'),
	Array(4197,'Wintergrasp'),
	Array(66,'Zul\'Drak'),
  ),
);

$COUNTRY = array(
	'00' => 'Other',
	'AF' => 'Afghanistan',
	'AL' => 'Albania',
	'dz' => 'Algeria',
	'AS' => 'American Samoa',
	'AD' => 'Andorra',
	'AO' => 'Angola',
	'AI' => 'Anguilla',
	'AQ' => 'Antarctica',
	'AG' => 'Antigua and Barbuda',
	'AR' => 'Argentina',
	'AM' => 'Armenia',
	'AW' => 'Aruba',
	'AU' => 'Australia',
	'AT' => 'Austria',
	'AZ' => 'Azerbaijan',
	'BH' => 'Bahrain',
	'BD' => 'Bangladesh',
	'BB' => 'Barbados',
	'BY' => 'Belarus',
	'BE' => 'Belgium',
	'BZ' => 'Belize',
	'BJ' => 'Benin',
	'BM' => 'Bermuda',
	'BT' => 'Bhutan',
	'BO' => 'Bolivia',
	'BA' => 'Bosnia and Herzegovina',
	'BW' => 'Botswana',
	'BV' => 'Bouvet Island',
	'BR' => 'Brazil',
	'IO' => 'British Indian Ocean Territory',
	'VG' => 'British Virgin Islands',
	'BN' => 'Brunei Darussalam',
	'BG' => 'Bulgaria',
	'BF' => 'Burkina Faso',
	'MM' => 'Burma',
	'BI' => 'Burundi',
	'KH' => 'Cambodia',
	'CM' => 'Cameroon',
	'CA' => 'Canada',
	'CV' => 'Cape Verde',
	'KY' => 'Cayman Islands',
	'CF' => 'Central African Republic',
	'TD' => 'Chad',
	'CL' => 'Chile',
	'CN' => 'China',
	'CX' => 'Christmas Island',
	'CC' => 'Cocos (Keeling) Islands',
	'CO' => 'Colombia',
	'KM' => 'Comoros',
	'CD' => 'Congo, Democratic Republic of the',
	'CG' => 'Congo, Republic of the',
	'CK' => 'Cook Islands',
	'CR' => 'Costa Rica',
	'CI' => 'Cote d`Ivoire',
	'HR' => 'Croatia',
	'CU' => 'Cuba',
	'CY' => 'Cyprus',
	'CZ' => 'Czech Republic',
	'DK' => 'Denmark',
	'DJ' => 'Djibouti',
	'DM' => 'Dominica',
	'DO' => 'Dominican Republic',
	'TP' => 'East Timor',
	'EC' => 'Ecuador',
	'EG' => 'Egypt',
	'SV' => 'El Salvador',
	'GQ' => 'Equatorial Guinea',
	'ER' => 'Eritrea',
	'EE' => 'Estonia',
	'ET' => 'Ethiopia',
	'FK' => 'Falkland Islands (Islas Malvinas)',
	'FO' => 'Faroe Islands',
	'FJ' => 'Fiji',
	'FI' => 'Finland',
	'FR' => 'France',
	'FX' => 'France, Metropolitan',
	'GF' => 'French Guiana',
	'PF' => 'French Polynesia',
	'TF' => 'French Southern and Antarctic Lands',
	'GA' => 'Gabon',
	'GE' => 'Georgia',
	'DE' => 'Germany',
	'GH' => 'Ghana',
	'GI' => 'Gibraltar',
	'GR' => 'Greece',
	'GL' => 'Greenland',
	'GD' => 'Grenada',
	'GP' => 'Guadeloupe',
	'GU' => 'Guam',
	'GT' => 'Guatemala',
	'GG' => 'Guernsey',
	'GN' => 'Guinea',
	'GW' => 'Guinea-Bissau',
	'GY' => 'Guyana',
	'HT' => 'Haiti',
	'HM' => 'Heard Island and McDonald Islands',
	'VA' => 'Holy See (Vatican City)',
	'HN' => 'Honduras',
	'HK' => 'Hong Kong (SAR)',
	'HU' => 'Hungary',
	'IS' => 'Iceland',
	'IN' => 'India',
	'ID' => 'Indonesia',
	'IR' => 'Iran',
	'IQ' => 'Iraq',
	'IE' => 'Ireland',
	'IL' => 'Israel',
	'IT' => 'Italy',
	'JM' => 'Jamaica',
	'JP' => 'Japan',
	'JE' => 'Jersey',
	'JO' => 'Jordan',
	'KZ' => 'Kazakhstan',
	'KE' => 'Kenya',
	'KI' => 'Kiribati',
	'KP' => 'Korea, North',
	'KR' => 'Korea,  South',
	'KW' => 'Kuwait',
	'KG' => 'Kyrgyzstan',
	'LA' => 'Laos',
	'LV' => 'Latvia',
	'LB' => 'Lebanon',
	'LS' => 'Lesotho',
	'LR' => 'Liberia',
	'LY' => 'Libya',
	'LI' => 'Liechtenstein',
	'LT' => 'Lithuania',
	'LU' => 'Luxembourg',
	'MO' => 'Macao',
	'MK' => 'Macedonia, The Former Yugoslav Republic of',
	'MG' => 'Madagascar',
	'MW' => 'Malawi',
	'MY' => 'Malaysia',
	'MV' => 'Maldives',
	'ML' => 'Mali',
	'MT' => 'Malta',
	'IM' => 'Man, Isle of',
	'MH' => 'Marshall Islands',
	'MQ' => 'Martinique',
	'MR' => 'Mauritania',
	'MU' => 'Mauritius',
	'YT' => 'Mayotte',
	'MX' => 'Mexico',
	'FM' => 'Micronesia, Federated States of',
	'MD' => 'Moldova',
	'MC' => 'Monaco',
	'MN' => 'Mongolia',
	'MS' => 'Montserrat',
	'MA' => 'Morocco',
	'MZ' => 'Mozambique',
	'NA' => 'Namibia',
	'NR' => 'Nauru',
	'NP' => 'Nepal',
	'NL' => 'Netherlands',
	'AN' => 'Netherlands Antilles',
	'NC' => 'New Caledonia',
	'NZ' => 'New Zealand',
	'NI' => 'Nicaragua',
	'NE' => 'Niger',
	'NG' => 'Nigeria',
	'NU' => 'Niue',
	'NF' => 'Norfolk Island',
	'MP' => 'Northern Mariana Islands',
	'NO' => 'Norway',
	'OM' => 'Oman',
	'PK' => 'Pakistan',
	'PW' => 'Palau',
	'PS' => 'Palestinian Territory, Occupied',
	'PA' => 'Panama',
	'PG' => 'Papua New Guinea',
	'PY' => 'Paraguay',
	'PE' => 'Peru',
	'PH' => 'Philippines',
	'PN' => 'Pitcairn Islands',
	'PL' => 'Poland',
	'PT' => 'Portugal',
	'PR' => 'Puerto Rico',
	'QA' => 'Qatar',
	'RE' => 'Réunion',
	'RO' => 'Romania',
	'RU' => 'Russia',
	'RW' => 'Rwanda',
	'SH' => 'Saint Helena',
	'KN' => 'Saint Kitts and Nevis',
	'LC' => 'Saint Lucia',
	'PM' => 'Saint Pierre and Miquelon',
	'VC' => 'Saint Vincent and the Grenadines',
	'WS' => 'Samoa',
	'SM' => 'San Marino',
	'ST' => 'São Tomé and Príncipe',
	'SA' => 'Saudi Arabia',
	'SN' => 'Senegal',
	'SC' => 'Seychelles',
	'SL' => 'Sierra Leone',
	'SG' => 'Singapore',
	'SK' => 'Slovakia',
	'SI' => 'Slovenia',
	'SB' => 'Solomon Islands',
	'SO' => 'Somalia',
	'ZA' => 'South Africa',
	'GS' => 'South Georgia and the South Sandwich Islands',
	'ES' => 'Spain',
	'LK' => 'Sri Lanka',
	'SD' => 'Sudan',
	'SR' => 'Suriname',
	'SJ' => 'Svalbard',
	'SZ' => 'Swaziland',
	'SE' => 'Sweden',
	'CH' => 'Switzerland',
	'SY' => 'Syria',
	'TW' => 'Taiwan',
	'TJ' => 'Tajikistan',
	'TZ' => 'Tanzania',
	'TH' => 'Thailand',
	'BS' => 'The Bahamas',
	'GM' => 'The Gambia',
	'TG' => 'Togo',
	'TK' => 'Tokelau',
	'TO' => 'Tonga',
	'TT' => 'Trinidad and Tobago',
	'TN' => 'Tunisia',
	'TR' => 'Turkey',
	'TM' => 'Turkmenistan',
	'TC' => 'Turks and Caicos Islands',
	'TV' => 'Tuvalu',
	'UG' => 'Uganda',
	'UA' => 'Ukraine',
	'AE' => 'United Arab Emirates',
	'UK' => 'United Kingdom',
	'US' => 'United States',
	'UM' => 'United States Minor Outlying Islands',
	'UY' => 'Uruguay',
	'UZ' => 'Uzbekistan',
	'VU' => 'Vanuatu',
	'VE' => 'Venezuela',
	'VN' => 'Vietnam',
	'VI' => 'Virgin Islands',
	'WF' => 'Wallis and Futuna',
	'EH' => 'Western Sahara',
	'YE' => 'Yemen',
	'YU' => 'Yugoslavia',
	'ZM' => 'Zambia',
	'ZW' => 'Zimbabwe'
);

$GMT = array(
	-12 => array('-12:00', 'Eniwetok, Kwajalein'),
	-11 => array('-11:00', 'Midway Island, Samoa'),
	-10 => array('-10:00', 'Hawaii'),
	-9 => array('-9:00', 'Alaska'),
	-8 => array('-8:00', 'Pacific Time (US & Canada)'),
	-7 => array('-7:00', 'Mountain Time (US & Canada)'),
	-6 => array('-6:00', 'Central Time (US & Canada), Mexico City'),
	-5 => array('-5:00', 'Eastern Time (US & Canada), Bogota, Lima'),
	-4 => array('-4:00', 'Atlantic Time (Canada), Caracas, La Paz'),
	-3 => array('-3:00', 'Brazil, Buenos Aires, Georgetown'),
	-2 => array('-2:00', 'Mid-Atlantic'),
	-1 => array('-1:00', 'Azores, Cape Verde Islands'),
	0 => array('+0:00', 'Western Europe Time, London, Lisbon, Casablanca'),
	1 => array('+1:00', 'Brussels, Copenhagen, Madrid, Paris'),
	2 => array('+2:00', 'Kaliningrad, South Africa'),
	3 => array('+3:00', 'Baghdad, Riyadh, Moscow, St. Petersburg'),
	4 => array('+4:00', 'Abu Dhabi, Muscat, Baku, Tbilisi'),
	5 => array('+5:00', 'Ekaterinburg, Islamabad, Karachi, Tashkent'),
	6 => array('+6:00', 'Almaty, Dhaka, Colombo'),
	7 => array('+7:00', 'Bangkok, Hanoi, Jakarta'),
	8 => array('+8:00', 'Beijing, Perth, Singapore, Hong Kong'),
	9 => array('+9:00', 'Tokyo, Seoul, Osaka, Sapporo, Yakutsk'),
	10 => array('+10:00', 'Eastern Australia, Guam, Vladivostok'),
	11 => array('+11:00', 'Magadan, Solomon Islands, New Caledonia'),
	12 => array('+12:00', 'Auckland, Wellington, Fiji, Kamchatka')
);

$PASSWORD_QUESTION = array(
	1 => $_LANG['CONF_CLASSES']['PQ_1'],
	2 => $_LANG['CONF_CLASSES']['PQ_2'],
	3 => $_LANG['CONF_CLASSES']['PQ_3'],
	4 => $_LANG['CONF_CLASSES']['PQ_4'],
	5 => $_LANG['CONF_CLASSES']['PQ_5'],
	6 => $_LANG['CONF_CLASSES']['PQ_6']
);

$FORUM_GROUP = array(
	0 => $_LANG['CONF_CLASSES']['FG_0'],
	1 => $_LANG['CONF_CLASSES']['FG_1'],
	2 => $_LANG['CONF_CLASSES']['FG_2'],
	3 => $_LANG['CONF_CLASSES']['FG_3'],
	4 => $_LANG['CONF_CLASSES']['FG_4'],
	5 => $_LANG['CONF_CLASSES']['FG_5'],
	6 => $_LANG['CONF_CLASSES']['FG_6']
);

$USER_LEVEL = array(
	0 => $_LANG['CONF_CLASSES']['UL_0'],
	1 => $_LANG['CONF_CLASSES']['UL_1'],
	2 => $_LANG['CONF_CLASSES']['UL_2'],
	3 => $_LANG['CONF_CLASSES']['UL_3'],
	4 => $_LANG['CONF_CLASSES']['UL_4'],	
);

$REALM_TYPE = array(
	0 => 'Normal',
	1 => 'PvP',
	4 => 'RP',
	8 => 'RPPvP',
);

$CHAR_CLASS = array(
	1 => 'Warrior',
	2 => 'Paladin',
	3 => 'Hunter',
	4 => 'Rogue',
	5 => 'Priest',
    6 => 'DeathKnight',
	7 => 'Shaman',
	8 => 'Mage',
	9 => 'Warlock',
	11 => 'Druid'
);

$CHAR_PROFESSION = array(
	164 => 'Blacksmithing',
	165 => 'Leatherworking',
	171 => 'Alchemy',
	182 => 'Herbalism',
	186 => 'Mining',
	197 => 'Tailoring',
	202 => 'Enginering',
	333 => 'Enchanting',
	393 => 'Skinning',
	755 => 'Jewelcrafting',
    773 => 'Inscription',
);

$CHAR_FACTION = array(
	0 => 'Alliance',
	1 => 'Horde'
);

$CHAR_RACE = array(
	1 => array('Human', 0),
	2 => array('Orc', 1),
	3 => array('Dwarf',  0),
	4 => array('Night Elf', 0),
	5 => array('Undead', 1),
	6 => array('Tauren', 1),
	7 => array('Gnome',  0),
	8 => array('Troll', 1),
	10 => array('Blood Elf', 1),
	11 => array('Draenei',  0),
);

$TICKET_CATEGORY = array(
	0 => 'Other',
	1 => 'Stuck',
	2 => 'Behavior',
	3 => 'Guild',
	4 => 'Item',
	5 => 'Environmental',
	6 => 'Creep',
	7 => 'Quest',
	8 => 'Technical',
	9 => 'Account',
	10 => 'Character',
);

$CHAR_RANK = array(
    0 => array(
		'00' => 'None',
		'01' => 'None',
		0 => 'None',
		1 => 'Private',
		2 => 'Corporal',
		3 => 'Sergeant',
		4 => 'Master Sergeant',
		5 => 'Sergeant Major',
		6 => 'Knight',
		7 => 'Knight-Lieutenant',
		8 => 'Knight-Captain',
		9 => 'Knight-Champion',
		10 => 'Lieutenant Commander',
		11 => 'Commander',
		12 => 'Marshal',
		13 => 'Field Marshal',
		14 => 'Grand Marshal'
    ),
    1 => array(
		'00' => 'None',
		'01' => 'None',
		0 => 'None',
		1 => 'Scout',
		2 => 'Grunt',
		3 => 'Sergeant',
		4 => 'Senior Sergeant',
		5 => 'First Sergeant',
		6 => 'Stone Guard',
		7 => 'Blood Guard',
		8 => 'Legionnare',
		9 => 'Centurion',
		10 => 'Champion',
		11 => 'Lieutenant General',
		12 => 'General',
		13 => 'Warlord',
		14 => 'High Warlord'
    )
)

?>