<?php
$language = array(
"title" => "Votesystem von",
"created_by" => "Erstellt von",

"wrong" => "Falscher Benutzername und/oder Passwort",
"username" => "Accountname:",
"password" => "Passwort:",
"realm_name" => "Realm Name:",
"submit" => "Login",
"reset" => "Zurücksetzen",
"enter_name_and_pass" => "Gib deinen Accountnamen und dein Passwort ein.",
"not_entered_username" => "Kein Accountname angegeben!",
"not_entered_password" => "Kein Passwort angegeben!",

"logout" => "Logout",
"realm" => "Realm",
"ip" => "IP",
"cur_acc" => "Aktueller Account",
"points_1" => "Punkte",
"acc_points_today" => "Heutige Punkte",
"limit" => "Maximal",
"not_voted_yet" => "Du hast noch nicht gevoted.",
"last_vote" => "Dein letzter Vote war vor",
"voting_period" => "Du kannst einmal voten innerhalb von",
"show_vote" => "Vote-Panel",
"show_reward" => "Belohnungs-Panel",
"sites_reset_after" => "Die Spalte 'Gevoted' wird auf 'Nein' gesetzt in",
"choose_char_for_reward" => "Wähle den Charakter aus.",
"available_chars" => "Verfügbare Charaktere:",
"cur_char" => "Ausgewählter Charakter",

"days" => "Tagen",
"hours" => "Stunden",
"minutes_and" => "Minuten und",
"seconds" => "Sekunden",
"chose_site" => "Wähle die Seite zum Voten",
"voting_sites" => "Voting Seiten",
"voted" => "Gevoted",
"yes" => "Ja",
"no" => "Nein",
"status" => "Status",
"online" => "Online",
"offline" => "Offline",
"available_rewards" => "Verfügbare Belohnungen",
"points_2" => "Punkte",
"choose" => "Wählen",
"was_given" => "Gesendet:",
"to" => "an",

"vote_limit_reached" => "Du hast das tägliche Votelimit für diesen Account erreicht.",
"vote_tomorrow" => "Du kannst morgen wieder voten.",

"mail_subject" => "Vote Belohnung",
"mail_message" => "Vielen Dank fuer die Votes!",

"back_to_site" => "Zurück zur Hauptseite",
);
?>