<?php
$language = array(
"title" => "Vote System of",
"created_by" => "Created by",

"wrong" => "Wrong password and/or account name",
"username" => "Account name:",
"password" => "Password:",
"realm_name" => "Realm name:",
"submit" => "Login",
"reset" => "Reset",
"enter_name_and_pass" => "Enter your account name and password.",
"not_entered_username" => "Not entered Account name!",
"not_entered_password" => "Not entered Password!",

"logout" => "Log out",
"realm" => "Realm",
"ip" => "IP",
"cur_acc" => "Current account",
"points_1" => "Points",
"acc_points_today" => "Account points today",
"limit" => "Limit",
"not_voted_yet" => "You have not voted yet",
"last_vote" => "Your last vote was before",
"voting_period" => "You can vote once every",
"show_vote" => "Vote Panel",
"show_reward" => "Reward Panel",
"sites_reset_after" => "The 'Voted' ticks will be set to 'No' in",
"choose_char_for_reward" => "Choose character for rewarding",
"available_chars" => "Available characters",
"cur_char" => "Current character",

"days" => "days",
"hours" => "hours",
"minutes_and" => "minutes and",
"seconds" => "seconds",
"chose_site" => "Choose site to vote in",
"voting_sites" => "Voting sites",
"voted" => "Voted",
"yes" => "Yes",
"no" => "No",
"status" => "Status",
"online" => "Online",
"offline" => "Offline",
"available_rewards" => "Available rewards",
"points_2" => "points",
"choose" => "Choose",
"was_given" => "It was given",
"to" => "to",

"vote_limit_reached" => "You have reached the daily vote limit for this account.",
"vote_tomorrow" => "You can vote tomorrow.",

"mail_subject" => "From The Vote System",
"mail_message" => "Thank you for your votes!",

"back_to_site" => "Back to the main site",
);
?>